chore: bump depedencies
google/process.dart pull request #75
Opened 2023-05-30 09:37 UTC by ndelanou

Upgrade project dependencies, blocking other packages that also depend on it to upgrade (e.g. `melos` and `dart_code_metrics` via `pub_updater`)

All test passed.

2023-06-12 19:04 UTC, Gustl22 requested changes

2023-06-12 19:04 UTC, Gustl22 commented on pubspec.yaml
> +  file: '^7.0.0'
You may can use `file: '>=6.0.0 <8.0.0'` as there weren't any changes which had to be made and it provides much broader compatibility.

2023-06-12 19:04 UTC, Gustl22 commented on pubspec.yaml
> +  lints: ^2.1.0
```suggestion
  lints: '>=1.0.1 <3.0.0'
```
Same for lints: `lints: '>=1.0.1 <3.0.0'`

2023-06-12 19:08 UTC, Gustl22 commented
This affects all Linux implementations, e.g. in [`path_provider`](https://github.com/flutter/packages/blob/main/packages/path_provider/path_provider_linux/pubspec.yaml), [xdg_directories](https://github.com/flutter/packages/blob/2d573fe913ebddeacb4ea869461b3b419aa48b5b/packages/xdg_directories/pubspec.yaml#L16), as one can't upgrade to `file >= 7.0.0` @jonahwilliams @tvolkert

2023-07-06 05:30 UTC, SirBarksALot approved these changes

2023-07-12 22:29 UTC, bernaferrari commented
cc @jakemac53 could you help this land/

2023-07-13 14:17 UTC, jakemac53 commented
I am not really affiliated with this package at all, it looks like @gspencergoog or @jonahwilliams have done some work though.

We do need a pubspec/changelog update for a new version (can just be a patch release, so `5.0.1`).

2023-07-13 21:23 UTC, gspencergoog commented
This looks fine to me, but it does need to have the CHANGELOG updated and the version bumped, as @jakemac53 said.

2023-08-08 19:56 UTC, closed without merging